eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
      instance:
        preferedIpAddress: true

spring:
  jpa:
    showSql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
